### PR TITLE
updated chroma.js to v1.1.1

### PR DESCRIPTION
**Pull request by bkuri**

### CODE REVIEW

**Comment by rcy** [comment]
Thanks @bkuri!

**Comment by bkuri** [comment]
@rcy no problem! Would you mind updating it in atmosphere when you get the chance? I'd rather use the official package instead of my local copy. TIA! :+1:

**Comment by rcy** [comment]
Should be done, I published 1.1.1.

**Comment by bkuri** [comment]
Yup, looks like it took a little longer than usual. Thanks again!

**Pull request merged**
